### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by deeplook** [FelixGSE/pyano#10]
I'm asking because the packaging of 0.1.0 seems to list unused dependencies like numpy, unnecessarily pin dependencies and install other dependencies only needed for develoopment like tox, flake8, pyflakes, and pytest, causing conflicts in existing environments.

**Comment by FelixGSE** [comment]
Hi @deeplook, sorry for my late reply. There are quite a few things that I plan to improve and refactor (dependency management being one of it). However, I am very occupied with work at the moment and think I won't have time to work on this project in the next few weeks.
